package com.example.hospitalmanagement.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * This class represents the AdmissionState entity, which is used to track the admission details of a patient in the hospital.
 * It includes information such as the entering date, exiting date, cause of admission, reason for discharge, and whether the patient has been discharged.
 */
@Getter // Lombok annotation to automatically generate getter methods for all fields.
@Setter // Lombok annotation to automatically generate setter methods for all fields.
@Entity // Marks this class as a JPA entity, meaning it will be mapped to a database table.
public class AdmissionState {

    /**
     * The unique identifier for the admission record.
     * This field is automatically generated by the database using an identity column.
     */
    @Id // Marks this field as the primary key of the entity.
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies that the primary key is auto-incremented by the database.
    private Long id;

    /**
     * The date and time when the patient was admitted to the hospital.
     * This field is initialized to the current date and time by default.
     */
    private LocalDateTime enteringDate = LocalDateTime.now();

    /**
     * The date and time when the patient was discharged from the hospital.
     * This field is optional and can be null if the patient is still admitted.
     */
    private LocalDateTime exitingDate;

    /**
     * The cause or reason for the patient's admission.
     */
    private String cause;

    /**
     * The reason for the patient's discharge (if applicable).
     */
    private String reason;

    /**
     * Indicates whether the patient has been discharged.
     * This field is initialized to `false` by default.
     */
    private boolean discharge = false;

    /**
     * The patient associated with this admission record.
     * This field establishes a many-to-one relationship with the Patient entity.
     */
    @ManyToOne // Specifies a many-to-one relationship with the Patient entity.
    @JoinColumn(name = "patient_id", nullable = false) // Specifies the foreign key column in the database and ensures it cannot be null.
    private Patient patient;

    /**
     * Default constructor.
     * Required for JPA to create instances of this class during data retrieval.
     */
    public AdmissionState() {}

    /**
     * Constructor with required fields.
     * Useful for creating instances of this class with predefined values.
     *
     * @param patient The patient associated with this admission record.
     * @param cause The cause or reason for the patient's admission.
     * @param enteringDate The date and time when the patient was admitted.
     */
    public AdmissionState(Patient patient, String cause, LocalDateTime enteringDate) {
        this.patient = patient;
        this.cause = cause;
        this.enteringDate = enteringDate;
    }
}